---
apiVersion: v1
kind: Pod
metadata:
  name: qb-test-pod
  labels:
    app: qb-test-pod
spec:
  volumes:
    - name: quobyte-backend
      persistentVolumeClaim:
        claimName: test-pvc
        readOnly: false
  nodeSelector:
    storage-node-pool: quobyte
  containers:
    - name: app
      # We use the quobyte client image only to obtain the tool "qinfo" 
      # That tool allows us to inspect files like this: "qinfo info <fileName>" 
      # It also allows us to see how we are authenticated: "qinfo whoami"
      image: quay.io/quobyte/quobyte-client:5 
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
      volumeMounts:
        - name: quobyte-backend
          mountPath: /mnt/quobyte-volume
