- hosts: localhost
  become: yes
  tasks:
    - name: Get elbencho binary archive
      get_url: 
        #url: https://github.com/breuner/elbencho/releases/download/v2.2-5/elbencho-static-x86_64.tar.gz
        url: https://github.com/breuner/elbencho/releases/download/v3.0-7/elbencho-static-x86_64.tar.gz 
        dest: /tmp/elbencho.tar.gz

    - name: Unpack elbencho archive
      unarchive:
        src: /tmp/elbencho.tar.gz
        dest: /tmp/
          

    - name: Create benchmark directory
      file:
        path: /home/deploy/benchmarks
        state: directory
        owner: deploy
        mode: '0755'

    - name: Create benchmark results directory
      file:
        path: /home/deploy/benchmarks/results
        state: directory
        owner: deploy
        mode: '0755'

# Clients are used for actual storage benchmarks
    - name: Create client list
      lineinfile:
        path: /home/deploy/benchmarks/elbencho-clients.list
        create: true
        line: "{{ item }}"
      with_items: "{{ groups.clients }}"

    - name: Create first client file
      lineinfile:
        path: /home/deploy/benchmarks/elbencho-firstclient.list
        create: true
        line: "{{ item }}"
      with_items: "{{ groups.clients[0] }}"

    - name: Create second client file
      lineinfile:
        path: /home/deploy/benchmarks/elbencho-secondclient.list
        create: true
        line: "{{ item }}"
      with_items: "{{ groups.clients[1] }}"


# All other nodes are used for "netbench"
    - name: Create dataserver list
      lineinfile:
        path: /home/deploy/benchmarks/elbencho-dataserver.list
        create: true
        line: "{{ item }}"
      with_items: "{{ groups.dataservices }}"

    - name: Create first dataservice file 
      lineinfile:
        path: /home/deploy/benchmarks/elbencho-firstdataserver.list
        create: true
        line: "{{ item }}"
      with_items: "{{ groups.dataservices[0] }}"

    - name: Create second dataservice file
      lineinfile:
        path: /home/deploy/benchmarks/elbencho-seconddataserver.list
        create: true
        line: "{{ item }}"
      with_items: "{{ groups.dataservices[1] }}"


- hosts: quobyteservers,clients 
  become: yes
  tasks:
    - name: Deploy elbencho binary 
      copy:
       src: /tmp/elbencho
       dest: /usr/local/bin/elbencho
       mode: "755"
       force: yes


