- hosts: registryservices[0]
  ignore_errors: yes
  vars_files:
    - /home/deploy/quobyte-ansible/vars/ansible-vars
  become: yes
  vars: 
    - my_volume_prefix: "r"
  tasks:
    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: Create volumes
      with_sequence: start=0 end=29 
      shell:
        cmd: qmgmt -u {{ api_service }} volume create "{{ my_volume_prefix }}{{ item }}" deploy deploy 

