- hosts: registryservices[0] 
  vars_files:
    - vars/ansible-vars
    - /home/deploy/quobyte-ansible/vars/ansible-vars
  become: yes
  tasks:
    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: Create policy 
      shell:
        cmd: qmgmt -u {{ api_service }} policy-rule import /home/deploy/quobyte-presales/elbencho/templates/policies.txt 


