---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quobyte-reg
spec:
  selector:
    matchLabels:
      app: quobyte-reg # has to match .spec.template.metadata.labels
  serviceName: "quobyte"
  replicas: {{ .Values.quobyte.replicas }}  
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: quobyte-reg # has to match .spec.selector.matchLabels
      annotations:
        timestamp: "{{ now }}"
    spec:
      subdomain: "quobyte"
      terminationGracePeriodSeconds: 10
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: {{ .Values.taintKey }}
        operator: "Exists"
          #value: {{ .Values.taintValue }}
        effect: "NoSchedule"
      initContainers:
      - name: quobyte-reg-pre 
        image: {{ .Values.quobyte.image }}
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: QUOBYTE_DATA_PORT 
            value: "7863"
          - name: QUOBYTE_META_PORT
            value: "7862"
          - name: QUOBYTE_REG_PORT 
            value: "7861"
          - name: QUOBYTE_API_PORT
            value: "7860" 
          - name: QUOBYTE_S3_PORT
            value: "8484" 
          - name: QUOBYTE_SERVICE
            value: registry
          - name: CLOUD_INSTALL
            value: "1" 
          - name: CLUSTER_NS
            value: {{ .Release.Namespace }}
          - name: LIMIT_OPEN_FILES
            value: "{{ .Values.quobyte.maxopenfiles }}"
          - name: LIMIT_MAX_PROCESSES
            value: "{{ .Values.quobyte.maxprocs }}"
        volumeMounts:
          - name: registry
            mountPath: /var/lib/quobyte/devices/registry
        # The first pod will bootstrap a cluster, any other pod will join.
        command:
              - /bin/bash
              - -xc
              - |
                NODENUM=$(echo "$NODENAME" | tr -dc "0-9")
                if [ ! -e /var/lib/quobyte/devices/registry/QUOBYTE_DEV_SETUP ]; then
                  if [[ $NODENUM == 0 ]]; then
                    /usr/bin/qbootstrap -y -d /var/lib/quobyte/devices/registry
                  else
                    /usr/bin/qmkdev -d -t REGISTRY /var/lib/quobyte/devices/registry
                  fi
                fi
      containers:
      - name: quobyte-reg
        image: {{ .Values.quobyte.image }}
        imagePullPolicy: Always
        env:
          - name: SERVICE_UUID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: QUOBYTE_DATA_PORT 
            value: "7863"
          - name: QUOBYTE_META_PORT
            value: "7862"
          - name: QUOBYTE_REG_PORT 
            value: "7861"
          - name: QUOBYTE_API_PORT
            value: "7860" 
          - name: QUOBYTE_S3_PORT
            value: "8484" 
          - name: QUOBYTE_SERVICE
            value: registry
          - name: CLOUD_INSTALL
            value: "1" 
          - name: CLUSTER_NS
            value: {{ .Release.Namespace }}
          - name: QUOBYTE_REGISTRY
            value: _quobyte._tcp.quobyte.{{ .Release.Namespace }}.{{ .Values.clusterDnsSuffix }}
          - name: LIMIT_OPEN_FILES
            value: "{{ .Values.quobyte.maxopenfiles }}"
          - name: LIMIT_MAX_PROCESSES
            value: "{{ .Values.quobyte.maxprocs }}"
          {{- if .Values.quobyte.enable_rdma.registry }}
          - name: QUOBYTE_ENABLE_RDMA
            value: "{{ .Values.quobyte.enable_rdma.registry }}"
          {{- end }}
          {{- if .Values.quobyte.memory.maxmem.registry }}
          - name: QUOBYTE_MAX_MEM_REGISTRY
            value: "{{ .Values.quobyte.memory.maxmem.registry }}"
          {{- end}}
          {{- if .Values.quobyte.memory.maxbuffer.other }}
          - name: QUOBYTE_MAX_BUFFER_OTHER
            value: "{{ .Values.quobyte.memory.maxbuffer.other }}"
          {{- end}}
        ports:
          - containerPort: 7861
            name: quobyte-reg
          - containerPort: 7861
            name: reg-ping
            protocol: UDP
          - containerPort: 7871
            name: quobyte-health
        volumeMounts:
          - name: registry
            mountPath: /var/lib/quobyte/devices/registry
        livenessProbe:
          httpGet:
            path: /serviceHealth
            port: quobyte-health
      {{- if .Values.nodepoolname }}
      nodeSelector:
           storage-node-pool: {{ .Values.nodepoolname }}
      {{- end }}
      affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - quobyte-reg
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: registry
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $.Values.quobyte.storageclassRegistry }} 
      resources:
        requests:
          storage: 25Gi
      {{- if eq $.Values.nodepoolname "quobyte-local" }}
      selector:
        matchLabels:
          role: "registry"
      {{- end }}

