- hosts: [ quobyteservers, clients ]
  become: yes
  tasks:
    
    - name: Install Debian packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
        allow_unauthenticated: "{{ check_packages_signature | default('no', false) }}"
      vars:
        packages:
        - iperf3 
      when: ansible_facts['os_family'] == "Debian"
 
    - name: Install RPM packages
      yum: 
        update_cache: yes
        allow_downgrade: yes
        state: present
        name: "{{ packages }}"
      vars:
        packages:
        - iperf3 
      when: ansible_facts['os_family'] == "RedHat" 

    - name: Install RPM packages on Suse Linux 
      zypper: 
        update_cache: yes
        oldpackage: yes
        state: present
        name: "{{ packages }}"
      vars:
        packages:
        - iperf3 
      when: ansible_facts['os_family'] == "Suse"

- hosts: quobyteservers
  remote_user: deploy
  tasks:
  - name: start server iperf
    shell: iperf3 --server --daemon

- hosts: localhost 
  tasks:
  - name: Create results directory
    file:
      path: /home/deploy/iperf_results
      state: directory
      mode: '0755'
      
- hosts: clients[0]
  remote_user: deploy
  tasks:
  - name: set iperf server
    set_fact: iperf_server="{{ groups['quobyteservers'].0 }}"
  - name: start client iperf
    shell: "iperf3 --client {{ iperf_server }} > /home/deploy/iperf-client-server"
  - name: grab iperf output
    fetch: src="/home/deploy/iperf-client-server" dest=/home/deploy/iperf_results/ flat=yes

- hosts: quobyteservers[1]
  remote_user: deploy
  tasks:
  - name: set iperf server
    set_fact: iperf_server="{{ groups['quobyteservers'].0 }}"
  - name: start server iperf
    shell: "iperf3 --client {{ iperf_server }} > /home/deploy/iperf-server-server"
  - name: grab iperf output
    fetch: src="/home/deploy/iperf-server-server" dest=/home/deploy/iperf_results/ flat=yes

- hosts: quobyteservers[0]
  remote_user: deploy
  tasks:
  - name: set iperf server
    set_fact: iperf_server="{{ groups['quobyteservers'].0 }}"
  - name: Test machine local interface
    shell: "iperf3 --client {{ iperf_server }} > /home/deploy/iperf-server-localhost"
  - name: grab iperf output
    fetch: src="/home/deploy/iperf-server-localhost" dest=/home/deploy/iperf_results/ flat=yes
