- hosts: registryservices[0]
  become: yes
  vars_files:
    - /home/deploy/quobyte-ansible/vars/ansible-vars
  tasks:
  tasks:
    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: Create a list of on-prem devices
      shell:
        cmd: qmgmt -u {{ api_service }} device list --list-columns device_id,Host| grep "on-prem" | awk '{print $1}' 
      register: onprem_devices 

    - name: Create a list of cloud burst
      shell:
        cmd: qmgmt -u {{ api_service }} device list --list-columns device_id,Host| grep "burst" | awk '{print $1}' 
      register: burst_devices 

    - set_fact: 
       cleaned_onprem_devices: "{{ onprem_devices.stdout_lines }}"

    - set_fact: 
       cleaned_burst_devices: "{{ burst_devices.stdout_lines }}"

    - name: Tag on-prem devices
      shell:
        cmd: qmgmt -u {{ api_service }} device update add-tags {{ item }} on-premise 
      with_items: "{{ cleaned_onprem_devices }}" 

    - name: Tag burst devices
      shell:
        cmd: qmgmt -u {{ api_service }} device update add-tags {{ item }} burst
      with_items: "{{ cleaned_burst_devices }}" 

