
- hosts: registryservices[0] 
  vars_files:
    - /home/deploy/provisioning/vars/ansible-vars
  vars: 
    - my_tenant: "spready"
    - my_volume: "spreadOne"
  become: yes
  tasks:
    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: Test if tenant {{ my_tenant }} exists 
      shell:
        cmd: qmgmt -u {{ api_service }} tenant list | grep "^{{ my_tenant }} " | awk '{print $1}'
      register: my_tenant_test

    - name: Create tenant 
      shell:
        cmd: qmgmt -u {{ api_service }} tenant create {{ my_tenant }} 
      when: my_tenant not in my_tenant_test.stdout

    - name: Test if volume {{ my_volume }} exists 
      shell:
        cmd: qmgmt -u {{ api_service }} volume list | grep "^{{ my_volume }} " | awk '{print $1}'
      register: my_volume_test

    - name: Create volume using policy rules
      shell:
        cmd: qmgmt -u {{ api_service }} volume create "{{ my_tenant }}"/"{{ my_volume }}" root root 
      when: my_volume not in my_volume_test.stdout  
