- hosts: registryservices[0]
  vars_files:
    - /home/deploy/quobyte-ansible/vars/ansible-vars
  become: yes
  tasks:

    - name: Dump cluster config to variable 
      uri:
        url: "http://{{api_service}}:7860"
        user: "{{admin_user}}"
        password: "{{admin_password}}"
        force_basic_auth: yes
        method: POST
        body_format: json
        body: "{ \"id\": \"text\",\"jsonrpc\": \"2.0\", \"method\": \"getConfiguration\", \"params\": { \"configuration_type\": \"SYSTEM_CONFIGURATION\", \"retry\": \"INFINITELY\" } }"
        return_content: yes
      register: systemconfig_dump_raw 

    - name: Get systemconfig 
      set_fact: 
        systemconfig: "{{ systemconfig_dump_raw.json.result.system_configuration }}"

    - debug:
            var: systemconfig

    - name: Create new systemconfig
      set_fact:
        systemconfig_var: "{{ systemconfig_var | default([]) | combine({ 'method': 'setConfiguration', 'id': 'text', 'jsonrpc': '2.0', 'params': {'configuration_type': 'SYSTEM_CONFIGURATION', 'system_configuration': '{{ systemconfig }}' } }) }}"

    - name: Make sure Health Manager is enabled 
      set_fact:
        params: {'params': {'system_configuration': {'health_manager_config': {'enable': true }}}}

    - name: Activate Tiering Policy with 24h  interval
      set_fact:
        param2: {'params': {'system_configuration': {'health_manager_config': {'tiering_policy': {'enable': true, 'restrict_to_maintenance_window': false, 'interval_s': 86400} }}}} 

    - name: Deactivate automated Enforce Placement
      set_fact:
        param3: {'params': {'system_configuration': {'health_manager_config': {'enforce_placement_policy': {'enable': true, 'on_demand': false} }}}} 


    - name: Merge params
      set_fact:
        params: "{{ params|combine(param2, param3, recursive=True) }}"
      when: param3 is defined

    - name: Merge all settings
      set_fact:
        systemconfig_var: "{{ systemconfig_var|combine(params, recursive=True) }}"

    - debug:
        var: systemconfig_var

    - name: Write cluster config to Quobyte 
      uri:
        url: "http://{{api_service}}:7860"
        user: "{{admin_user}}"
        password: "{{admin_password}}"
        force_basic_auth: yes
        method: POST
        body_format: json
        body: "{{ systemconfig_var }}"
