

# architecture 
# number clients
- hosts: localhost
  become: yes
  tasks:
    - name: initialize empty list for devices
      set_fact:
        dataservice_nvme: []
        dataservice_sata: []
    - name: count services 
      set_fact: 
         number_clients: "{{ groups.clients | length }}"
         number_dataservices: "{{ groups.dataservices | length }}"
         number_metadataservices: "{{ groups.metadataservices | length }}"

# Data service
    - name: Delegate all facts from first dataserver
      setup:
      delegate_to: "{{ item }}" 
      delegate_facts: true 
      loop: "{{ [groups['dataservices'][0]] }}"
    - name: Collect processor type dataservices  
      #delegate_to: dataservices[0]
      set_fact: 
        dataservice_cpu_architecture: "{{ hostvars[groups['dataservices'][0]].ansible_architecture }}"
        dataservice_os:               "{{ hostvars[groups['dataservices'][0]].ansible_distribution }} {{ hostvars[groups['dataservices'][0]].ansible_distribution_version }}"
        dataservice_cpu_model:        "{{ hostvars[groups['dataservices'][0]].ansible_processor.2 }}"
        dataservice_cpu_cores:        "{{ hostvars[groups['dataservices'][0]].ansible_processor_count }}"
        dataservice_cpu_threads:      "{{ hostvars[groups['dataservices'][0]].ansible_processor_threads_per_core }}"
        dataservice_memory_total:     "{{ hostvars[groups['dataservices'][0]].ansible_memtotal_mb }} MB"
        dataservice_devices:          "{{ hostvars[groups['dataservices'][0]].ansible_devices }}"
    - name: Get SATA devices
      delegate_to: dataservices[1]
      delegate_facts: true
      set_fact:
        dataservice_sata: "{{ dataservice_sata + [item.key] }}"
      with_dict: "{{ dataservice_devices }}"
      when: "item.value.host.startswith('SATA controller:')"
    - name: Get NVMe devices
      delegate_to: dataservices[0]
      set_fact:
        dataservice_nvme: "{{ dataservice_nvme + [item.key] }}"
      with_dict: "{{ dataservice_devices }}"
      when: "item.value.host.startswith('Non-Volatile memory controller:')"
    - name: Count devices 
      set_fact: 
         dataservice_nvme_count: "{{ dataservice_nvme | length }}"
         dataservice_sata_count: "{{ dataservice_sata | length }}"


# Shared hosts or dedicated services?

# Summary
    - name: Write summary 
      template:
        src: templates/infra.jinja2
        dest: /tmp/infra-summary.txt

# policies in action
