apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: data
      app.kubernetes.io/name: quobyte-storage
      app.kubernetes.io/part-of: quobyte
      node: gke-localstorage-cluster-default-pool-153540ea-9bnn
      role: data
    name: pv-gke-localstorage-cluster-default-pool-153540ea-9bnn-data1
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 300Gi
    local:
      path: /var/lib/quobyte/devices/data1
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gke-localstorage-cluster-default-pool-153540ea-9bnn
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
    volumeMode: Filesystem
kind: List
metadata:
  resourceVersion: ""
