apiVersion: v1
kind: Secret
metadata:
  name: quobyte-secret 
type: "kubernetes.io/quobyte"
data:
    # "Tenant Admin" access key, base64 encoded
    ##accessKeyId: <yourEncodedKeyID> 
    accessKeyId: TFRSVFhxWXpsNkk3Z1dZUmJiem4= 
    ##accessKeySecret: <yourEncodedKeySecret>
    accessKeySecret: c09sS3p3UjVMUFZjMmp0Nzh0dTk3Zkl2eEs3Qnlub2lIVjZoT0cxSQ==

