kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc 
  annotations: {
    user-secret: "user-secret" 
  }
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: quobyte-simple 
  volumeName: test-volume
