- hosts: quobyteservers
  any_errors_fatal: false
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: Patch qmgmt 
      command:
        cmd: sed -i 's|#!/usr/bin/env python2|#!/usr/bin/env python3|g' /usr/bin/qmgmt 
