apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: metadata
      app.kubernetes.io/name: quobyte-storage
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: latpoc11
      role: metadata
    name: pv-latpoc11-metadata0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5800Gi
    local:
      path: /var/lib/quobyte/devices/metadata0
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - latpoc11
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: metadata
      app.kubernetes.io/name: quobyte-storage
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: latpoc12
      role: metadata
    name: pv-latpoc12-metadata0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5800Gi
    local:
      path: /var/lib/quobyte/devices/metadata0
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - latpoc12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: metadata
      app.kubernetes.io/name: quobyte-storage
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: latpoc13
      role: metadata
    name: pv-latpoc13-metadata0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5800Gi
    local:
      path: /var/lib/quobyte/devices/metadata0
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - latpoc13
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: metadata
      app.kubernetes.io/name: quobyte-storage
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: latpoc14
      role: metadata
    name: pv-latpoc14-metadata0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5800Gi
    local:
      path: /var/lib/quobyte/devices/metadata0
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - latpoc14
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
    volumeMode: Filesystem
kind: List
metadata:
  resourceVersion: ""
