apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: quobyte-registry
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: node1 
      role: registry-state
    name: pv-node1-registry0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    local:
      path: /var/lib/quobyte/devices/registry-state
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node1
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: quobyte-registry
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: node2 
      role: registry-state
    name: pv-node2-registry0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    local:
      path: /var/lib/quobyte/devices/registry-state
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node2
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: quobyte-registry
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: node3
      role: registry-state
    name: pv-node3-registry0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    local:
      path: /var/lib/quobyte/devices/registry-state
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node3
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: quobyte-registry
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: node4
      role: registry-state
    name: pv-node4-registry0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    local:
      path: /var/lib/quobyte/devices/registry-state
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node4
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
kind: List
metadata:
  resourceVersion: ""
