apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: quobyte-registry
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: latpoc11
      role: registry-state
    name: pv-latpoc11-registry0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    local:
      path: /var/lib/quobyte/devices/registry-state
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - latpoc11
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: quobyte-registry
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: latpoc12
      role: registry-state
    name: pv-latpoc12-registry0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    local:
      path: /var/lib/quobyte/devices/registry-state
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - latpoc12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: quobyte-registry
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: latpoc13
      role: registry-state
    name: pv-latpoc13-registry0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    local:
      path: /var/lib/quobyte/devices/registry-state
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - latpoc13
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      app.kubernetes.io/component: registry
      app.kubernetes.io/name: quobyte-registry
      app.kubernetes.io/part-of: quobyte
      index: "0"
      node: latpoc14
      role: registry-state
    name: pv-latpoc14-registry0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    local:
      path: /var/lib/quobyte/devices/registry-state
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - latpoc14
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-local
kind: List
metadata:
  resourceVersion: ""
