- hosts: dataservices
  vars_files:
    - vars/ansible-vars
  become: yes
  vars:
    devices1:
      - /dev/sdb
      - /dev/sdc
    devices2:
      - /dev/sdd
        #  - /dev/nvme0n1


  tasks:
    - name: Create config directory  
      ansible.builtin.file:
        path: "/etc/quobyte/{{ item }}"
        state: directory
        owner: quobyte 
        group: quobyte
      with_items: 
         - quobyte-data-1
         - quobyte-data-2

    - name: Create device test directories
      ansible.builtin.file:
        path: "/var/lib/quobyte/{{ item }}"
        state: directory
        owner: quobyte 
        group: quobyte
      with_items: 
         - data-1
         - data-2

    - name: Link devices into test directories 
      ansible.builtin.file:
        src: "{{ item }}" 
        dest: "/var/lib/quobyte/data-1/{{ item | basename }}"
        state: link
      with_items: "{{ devices1 }}"

    - name: Link devices into test directories 
      ansible.builtin.file:
        src: "/var/lib/quobyte/mnt/inspector-{{ item | basename}}" 
        dest: "/var/lib/quobyte/data-2/{{ item | basename }}"
        state: link
        force: yes
      with_items: "{{ devices2 }}"

    - name: Place service config for first service
      template:
        src: templates/quobyte-data-1.cfg
        dest: "/etc/quobyte/{{ item }}/data.cfg"
        owner: quobyte
        group: quobyte
      with_items: 
         - quobyte-data-1

    - name: Place service config for secondary service
      template:
        src: templates/quobyte-data-2.cfg
        dest: "/etc/quobyte/{{ item }}/data.cfg"
        owner: quobyte
        group: quobyte
      with_items: 
         - quobyte-data-2

    - name: Add systemd unit files
      template:
        src: templates/quobyte-data-number.service
        dest: "/etc/systemd/system/{{ item }}.service"
      with_items: 
         - quobyte-data-1
         - quobyte-data-2
           
#    - name: Create a xfs filesystem on {{ devices1 }}
#      filesystem:
#        fstype: xfs 
#        opts: -isize=1024 
#        dev: "{{ item }}"
#      with_items: "{{ devices1 }}"
#
#    - name: Create a xfs filesystem on {{ devices2 }}
#      filesystem:
#        fstype: xfs 
#        opts: -isize=1024 -L quobyte-dev
#        dev: "{{ item }}"
#      with_items: "{{ devices2 }}"
#
#    - name: Label device partition 1 
#      command:
#        cmd: xfs_admin -L data-1 {{ item }} 
#      with_items: "{{ devices1 }}"
#
#    - name: Label device partition 2 
#      command:
#        cmd: xfs_admin -L data-2 {{ item }} 
#      with_items: "{{ devices2 }}"
#
#    - name: Make sure device labels are up to date 
#      command:
#        cmd: partprobe {{ item }} 
#      with_items: "{{ devices1 }}"
#
#    - name: Make sure device labels are up to date 
#      command:
#        cmd: partprobe {{ item }} 
#      with_items: "{{ devices2 }}"
#
#    - name: Temp. device mount to create Quobyte devices
#      mount:
#        path: "/tmp{{ item }}"
#        src: "{{ item }}"
#        state: ephemeral
#        fstype: xfs
#      with_items: "{{ devices1 }}"
#
#    - name: Temp. device mount to create Quobyte devices
#      mount:
#        path: "/tmp{{ item }}"
#        src: "{{ item }}"
#        state: ephemeral
#        fstype: xfs
#      with_items: "{{ devices2 }}"
#
#    - name: Run qmkdev to create Quobyte device 
#      command:
#        cmd: /usr/bin/qmkdev -t DATA /tmp{{ item }}
#        creates: /tmp{{ item }}/QUOBYTE_DEV_SETUP
#      with_items: "{{ devices1 }}"
#
#    - name: Run qmkdev to create Quobyte device 
#      command:
#        cmd: /usr/bin/qmkdev -t DATA /tmp{{ item }}
#        creates: /tmp{{ item }}/QUOBYTE_DEV_SETUP
#      with_items: "{{ devices2 }}"
#
#    - name: Unmount temporary device mount
#      mount:
#        path: "/tmp{{ item }}"
#        src: "{{ item }}"
#        state: unmounted
#      with_items: "{{ devices1 }}"
#
#    - name: Unmount temporary device mount
#      mount:
#        path: "/tmp{{ item }}"
#        src: "{{ item }}"
#        state: unmounted
#      with_items: "{{ devices2 }}"
#
    - name: Disable Quobyte default data services
      service:
        enabled: yes
        state: stopped
        name: "{{ item }}"
      with_items: 
         - quobyte-data

    - name: Enable Quobyte data services
      service:
        enabled: yes
        state: restarted
        name: "{{ item }}"
      with_items: 
         - quobyte-data-1
         - quobyte-data-2

    - name: Wait for data service to signal readiness
      uri:
        url: 'http://localhost:7873/serviceHealth'
        return_content: no 
        validate_certs: no
        status_code:
        - 200
      until: uri_output.status == 200
      retries: 24
      delay: 5
      register: uri_output

