- hosts: registryservices[0] 
  vars_files:
    - /home/deploy/quobyte-ansible/vars/ansible-vars
  vars: 
    - my_tenant: "database"
    - my_user: "db-user"
  become: no
  tasks:
    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: Test if key for user {{ my_user }} exists 
      shell:
        cmd: qmgmt -u {{ api_service }} accesskey list | grep "^{{ my_user }} " | awk '{print $1}'
      register: my_user_test

    - name: Create Key 
      shell:
        cmd: qmgmt -u {{ api_service }} accesskey create DATA_ACCESS_KEY "{{ my_user }}" --tenant="{{ my_tenant }}" --validity-days=2
      when: my_user not in my_user_test.stdout

        #qmgmt accesskey create DATA_ACCESS_KEY db-user --tenant="database" --validity-days=2

