apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elbencho
  name: elbencho
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elbencho
  template:
    metadata:
      labels:
        app: elbencho
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - tail -f /dev/null
        image: breuner/elbencho
        name: elbencho
        volumeMounts:
        - mountPath: /mnt/quobyte-volume
          name: quobyte-backend
      volumes:
      - name: quobyte-backend
        persistentVolumeClaim:
          claimName: test-pvc
